-- PHASE 2 surgical rollback (recreate dropped leaks; drop added iso)

DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.clinic_health_analyses;
CREATE POLICY "clinic_health_analyses_all" ON public.clinic_health_analyses AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.clinic_medical_reports;
CREATE POLICY "clinic_medical_reports_all" ON public.clinic_medical_reports AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.clinic_medical_review_queue;
CREATE POLICY "clinic_medical_review_queue_all" ON public.clinic_medical_review_queue AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.clinic_post_care_schedule;
CREATE POLICY "clinic_post_care_tenant_isolation" ON public.clinic_post_care_schedule AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.clinic_prescriptions;
CREATE POLICY "clinic_prescriptions_tenant_isolation" ON public.clinic_prescriptions AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.clinic_video_scripts;
CREATE POLICY "clinic_video_scripts_all" ON public.clinic_video_scripts AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.workflow_health_log;
CREATE POLICY "rls_auth_read" ON public.workflow_health_log AS PERMISSIVE FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.credit_transactions;
CREATE POLICY "Authenticated access" ON public.credit_transactions AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.lead_gen_credit_logs;
CREATE POLICY "lead_gen_credit_logs_policy" ON public.lead_gen_credit_logs AS PERMISSIVE FOR ALL TO public USING (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.revenue_attribution;
CREATE POLICY "Allow authenticated" ON public.revenue_attribution AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "anon_read_revenue_attribution" ON public.revenue_attribution AS PERMISSIVE FOR SELECT TO public USING (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.revenue_forecasts;
CREATE POLICY "Allow authenticated" ON public.revenue_forecasts AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.sales_deals;
CREATE POLICY "Allow authenticated" ON public.sales_deals AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.ai_agent_conversations;
CREATE POLICY "ai_agent_conv_read" ON public.ai_agent_conversations AS PERMISSIVE FOR SELECT TO public USING (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.ai_agent_suggestions;
CREATE POLICY "ai_agent_sugg_read" ON public.ai_agent_suggestions AS PERMISSIVE FOR SELECT TO public USING (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.ai_agent_tasks;
CREATE POLICY "ai_agent_tasks_read" ON public.ai_agent_tasks AS PERMISSIVE FOR SELECT TO public USING (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.ai_feedback;
CREATE POLICY "Allow authenticated" ON public.ai_feedback AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.ai_generated_messages;
CREATE POLICY "Allow authenticated" ON public.ai_generated_messages AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.ai_task_templates;
CREATE POLICY "Allow authenticated" ON public.ai_task_templates AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.ai_tasks;
CREATE POLICY "Allow authenticated" ON public.ai_tasks AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.analytics_events;
CREATE POLICY "Allow authenticated" ON public.analytics_events AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.api_usage_logs;
CREATE POLICY "api_usage_logs_policy" ON public.api_usage_logs AS PERMISSIVE FOR ALL TO public USING (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.audit_log;
CREATE POLICY "Allow authenticated" ON public.audit_log AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.automation_audit_log;
CREATE POLICY "Allow authenticated" ON public.automation_audit_log AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.automation_rules;
CREATE POLICY "Allow authenticated" ON public.automation_rules AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.automation_settings;
CREATE POLICY "Allow authenticated" ON public.automation_settings AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.autonomous_workflows;
CREATE POLICY "Allow authenticated" ON public.autonomous_workflows AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.business_insights;
CREATE POLICY "Allow authenticated" ON public.business_insights AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.call_queue;
CREATE POLICY "allow_all_access" ON public.call_queue AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.call_records;
CREATE POLICY "allow_all_call_records" ON public.call_records AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.calls;
CREATE POLICY "Allow authenticated" ON public.calls AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.campaign_logs;
CREATE POLICY "Allow authenticated" ON public.campaign_logs AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.campaign_metrics;
CREATE POLICY "Allow authenticated" ON public.campaign_metrics AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.campaign_send_log;
CREATE POLICY "Allow authenticated" ON public.campaign_send_log AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.campaign_templates;
CREATE POLICY "Allow authenticated" ON public.campaign_templates AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.campaigns;
CREATE POLICY "Allow authenticated" ON public.campaigns AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.channel_configurations;
CREATE POLICY "Allow authenticated" ON public.channel_configurations AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.channel_messages;
CREATE POLICY "Allow authenticated" ON public.channel_messages AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.collections_field_visits;
CREATE POLICY "collections_field_visits_tenant_access" ON public.collections_field_visits AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.comm_analytics_daily;
CREATE POLICY "allow_read_comm_analytics" ON public.comm_analytics_daily AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY "allow_write_comm_analytics" ON public.comm_analytics_daily AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.companies;
CREATE POLICY "companies_allow_all" ON public.companies AS PERMISSIVE FOR ALL TO public USING (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.competitor_analysis;
CREATE POLICY "Allow authenticated read competitor_analysis" ON public.competitor_analysis AS PERMISSIVE FOR SELECT TO public USING (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.competitor_intelligence;
CREATE POLICY "ci_allow_all" ON public.competitor_intelligence AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.consent;
CREATE POLICY "allow_all_consent" ON public.consent AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.consent_records;
CREATE POLICY "Allow authenticated" ON public.consent_records AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.contact_channel_map;
CREATE POLICY "allow_read_contact_channel_map" ON public.contact_channel_map AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY "allow_write_contact_channel_map" ON public.contact_channel_map AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.contact_engagement_patterns;
CREATE POLICY "allow_all_engagement_patterns" ON public.contact_engagement_patterns AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.content_attribution;
CREATE POLICY "allow_all_content_attribution" ON public.content_attribution AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.content_performance;
CREATE POLICY "Allow authenticated" ON public.content_performance AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.conversation_merges;
CREATE POLICY "allow_all_conversation_merges" ON public.conversation_merges AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.conversation_messages;
CREATE POLICY "Allow authenticated" ON public.conversation_messages AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.conversation_ratings;
CREATE POLICY "allow_read_conversation_ratings" ON public.conversation_ratings AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY "allow_write_conversation_ratings" ON public.conversation_ratings AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.conversation_tag_assignments;
CREATE POLICY "allow_read_conv_tag_assign" ON public.conversation_tag_assignments AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY "allow_write_conv_tag_assign" ON public.conversation_tag_assignments AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.conversions;
CREATE POLICY "allow_all_access" ON public.conversions AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.customer_360;
CREATE POLICY "Allow authenticated" ON public.customer_360 AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.customer_identities;
CREATE POLICY "Allow authenticated" ON public.customer_identities AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.customer_loyalty;
CREATE POLICY "Allow all for customer_loyalty" ON public.customer_loyalty AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.customer_marketing_prefs;
CREATE POLICY "Allow authenticated" ON public.customer_marketing_prefs AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.customer_relationships;
CREATE POLICY "Allow authenticated" ON public.customer_relationships AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.customer_reviews;
CREATE POLICY "Allow authenticated" ON public.customer_reviews AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.customer_timeline;
CREATE POLICY "Allow authenticated" ON public.customer_timeline AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.daily_metrics;
CREATE POLICY "Allow authenticated" ON public.daily_metrics AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.deal_activities;
CREATE POLICY "allow_all_deal_activities" ON public.deal_activities AS PERMISSIVE FOR ALL TO public USING (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.delivery_connectors;
CREATE POLICY "Allow all for delivery_connectors" ON public.delivery_connectors AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.email_sequence_steps;
CREATE POLICY "Allow authenticated" ON public.email_sequence_steps AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.email_sequences;
CREATE POLICY "Allow authenticated" ON public.email_sequences AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.employer_branding_content;
CREATE POLICY "Allow authenticated" ON public.employer_branding_content AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.entity_links;
CREATE POLICY "Allow authenticated" ON public.entity_links AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.escalations;
CREATE POLICY "allow_all_access" ON public.escalations AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.estimation_learning_data;
CREATE POLICY "allow_all_learning" ON public.estimation_learning_data AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
CREATE POLICY "tenant_read_learning" ON public.estimation_learning_data AS PERMISSIVE FOR SELECT TO public USING (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.estimation_revisions;
CREATE POLICY "allow_read_estimation_revisions" ON public.estimation_revisions AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY "allow_write_estimation_revisions" ON public.estimation_revisions AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.hr_announcements;
CREATE POLICY "Authenticated access" ON public.hr_announcements AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.hr_asset_assignments;
CREATE POLICY "hr_asset_read" ON public.hr_asset_assignments AS PERMISSIVE FOR SELECT TO public USING (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.hr_audit_logs;
CREATE POLICY "Authenticated access" ON public.hr_audit_logs AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.hr_conversations;
CREATE POLICY "Allow authenticated" ON public.hr_conversations AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.hr_document_templates;
CREATE POLICY "Allow authenticated" ON public.hr_document_templates AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.hr_employee_documents;
CREATE POLICY "Allow authenticated" ON public.hr_employee_documents AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.hr_expense_claims;
CREATE POLICY "Authenticated access" ON public.hr_expense_claims AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.hr_interview_schedules;
CREATE POLICY "hr_interview_schedules_access" ON public.hr_interview_schedules AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.hr_payroll_periods;
CREATE POLICY "Allow authenticated" ON public.hr_payroll_periods AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.hr_policy_acknowledgments;
CREATE POLICY "Allow authenticated" ON public.hr_policy_acknowledgments AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.hr_recruitment_outreach;
CREATE POLICY "hr_recruitment_outreach_access" ON public.hr_recruitment_outreach AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.hr_survey_responses;
CREATE POLICY "Allow authenticated" ON public.hr_survey_responses AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.inbox_rotation_log;
CREATE POLICY "rl_read" ON public.inbox_rotation_log AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY "rl_write" ON public.inbox_rotation_log AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.insurance_claims;
CREATE POLICY "allow_read_insurance_claims" ON public.insurance_claims AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY "allow_write_insurance_claims" ON public.insurance_claims AS PERMISSIVE FOR ALL TO public USING (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.landing_page_submissions;
CREATE POLICY "landing_page_submissions_all" ON public.landing_page_submissions AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.lead_ai_analysis;
CREATE POLICY "lead_ai_analysis_policy" ON public.lead_ai_analysis AS PERMISSIVE FOR ALL TO public USING (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.lead_gen_saved_searches;
CREATE POLICY "lead_gen_saved_searches_policy" ON public.lead_gen_saved_searches AS PERMISSIVE FOR ALL TO public USING (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.lead_gen_search_logs;
CREATE POLICY "lead_gen_search_logs_policy" ON public.lead_gen_search_logs AS PERMISSIVE FOR ALL TO public USING (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.lead_gen_searches;
CREATE POLICY "lead_gen_searches_all" ON public.lead_gen_searches AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.lead_notifications;
CREATE POLICY "notif_read" ON public.lead_notifications AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY "notif_write" ON public.lead_notifications AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.leads;
CREATE POLICY "Allow authenticated" ON public.leads AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.linkedin_outreach_queue;
CREATE POLICY "Allow authenticated" ON public.linkedin_outreach_queue AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.marketing_analytics;
CREATE POLICY "Allow authenticated" ON public.marketing_analytics AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.marketing_consent;
CREATE POLICY "marketing_consent_all" ON public.marketing_consent AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.marketing_performance_log;
CREATE POLICY "allow_all_mar" ON public.marketing_performance_log AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.marketing_sequence_enrollments;
CREATE POLICY "Allow authenticated" ON public.marketing_sequence_enrollments AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.media_library;
CREATE POLICY "Allow authenticated" ON public.media_library AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.media_mentions;
CREATE POLICY "Allow authenticated" ON public.media_mentions AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.media_sources;
CREATE POLICY "Allow authenticated" ON public.media_sources AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.message_templates;
CREATE POLICY "Allow authenticated" ON public.message_templates AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.notifications;
CREATE POLICY "Allow authenticated" ON public.notifications AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.oauth_state_nonces;
CREATE POLICY "rls_service_all" ON public.oauth_state_nonces AS PERMISSIVE FOR ALL TO public USING (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.omega_approval_queue;
CREATE POLICY "allow_all_omega_approval_queue" ON public.omega_approval_queue AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.omega_feedback;
CREATE POLICY "allow_all_omega_feedback" ON public.omega_feedback AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.onboarding_checklists;
CREATE POLICY "Authenticated access" ON public.onboarding_checklists AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.onboarding_retry_queue;
CREATE POLICY "orq_allow_all" ON public.onboarding_retry_queue AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.ops_agent_performance;
CREATE POLICY "allow_all" ON public.ops_agent_performance AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.orchestrator_events;
CREATE POLICY "allow_all_access" ON public.orchestrator_events AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.packages;
CREATE POLICY "Allow authenticated" ON public.packages AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.page_analytics;
CREATE POLICY "anon_insert_pa" ON public.page_analytics AS PERMISSIVE FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "auth_all_page_analytics" ON public.page_analytics AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.pending_actions;
CREATE POLICY "Authenticated access" ON public.pending_actions AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "allow_all_pending_actions" ON public.pending_actions AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.predictive_scores;
CREATE POLICY "Allow authenticated" ON public.predictive_scores AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.premium_pages;
CREATE POLICY "auth_all_premium_pages" ON public.premium_pages AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.pricing_logs;
CREATE POLICY "Allow authenticated" ON public.pricing_logs AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.providers;
CREATE POLICY "Allow authenticated" ON public.providers AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.rate_limits;
CREATE POLICY "Allow authenticated" ON public.rate_limits AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.recruitment_campaigns;
CREATE POLICY "Allow authenticated" ON public.recruitment_campaigns AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.restaurant_inventory;
CREATE POLICY "Allow all for restaurant_inventory" ON public.restaurant_inventory AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.restaurant_kitchen_display;
CREATE POLICY "Allow all for restaurant_kitchen_display" ON public.restaurant_kitchen_display AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.restaurant_orders;
CREATE POLICY "Allow all for restaurant_orders" ON public.restaurant_orders AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.review_response_templates;
CREATE POLICY "Allow authenticated" ON public.review_response_templates AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.sales_analytics_daily;
CREATE POLICY "Allow authenticated" ON public.sales_analytics_daily AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.sales_calls;
CREATE POLICY "tenant_isolation" ON public.sales_calls AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.sales_lead_assignments;
CREATE POLICY "Allow authenticated" ON public.sales_lead_assignments AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.scheduled_messages;
CREATE POLICY "allow_all_scheduled_messages" ON public.scheduled_messages AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.video_templates;
CREATE POLICY "anon_read_video_templates" ON public.video_templates AS PERMISSIVE FOR SELECT TO anon USING (true);
CREATE POLICY "auth_read_video_templates" ON public.video_templates AS PERMISSIVE FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.warranty_tracking;
CREATE POLICY "allow_read_warranty" ON public.warranty_tracking AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY "allow_write_warranty" ON public.warranty_tracking AS PERMISSIVE FOR ALL TO public USING (true);