-- RLS REMEDIATION — surgical rollback (undo)

CREATE POLICY "akp_all" ON public.api_key_pool AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
CREATE POLICY "rls_service_all" ON public.tenant_oauth_grants AS PERMISSIVE FOR ALL TO public USING (true);
CREATE POLICY "rls_service_all" ON public.accounting_clients AS PERMISSIVE FOR ALL TO public USING (true);
CREATE POLICY "rls_service_all" ON public.accounting_invoices AS PERMISSIVE FOR ALL TO public USING (true);
CREATE POLICY "rls_service_all" ON public.accounting_jobs AS PERMISSIVE FOR ALL TO public USING (true);
CREATE POLICY "rls_service_all" ON public.accounting_payments AS PERMISSIVE FOR ALL TO public USING (true);
CREATE POLICY "rls_service_all" ON public.accounting_reminders AS PERMISSIVE FOR ALL TO public USING (true);
CREATE POLICY "rls_service_all" ON public.accounting_transactions AS PERMISSIVE FOR ALL TO public USING (true);
CREATE POLICY "rls_service_all" ON public.accounting_truelayer_connections AS PERMISSIVE FOR ALL TO public USING (true);
CREATE POLICY "activities_allow_all" ON public.activities AS PERMISSIVE FOR ALL TO public USING (true);
CREATE POLICY "Authenticated access" ON public.ad_accounts AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Authenticated access" ON public.ad_campaigns AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Authenticated access" ON public.ad_creatives AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Authenticated access" ON public.ad_performance_log AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.audit_logs;
CREATE POLICY "Anyone can insert audit logs" ON public.audit_logs AS PERMISSIVE FOR INSERT TO public WITH CHECK (true);
CREATE POLICY "allow_all_conversations_insert" ON public.conversations AS PERMISSIVE FOR INSERT TO public WITH CHECK (true);
CREATE POLICY "allow_all_conversations_read" ON public.conversations AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY "allow_all_conversations_update" ON public.conversations AS PERMISSIVE FOR UPDATE TO public USING (true) WITH CHECK (true);
CREATE POLICY "hr_ai_interviews_access" ON public.hr_ai_interviews AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
CREATE POLICY "rls_service_all" ON public.hr_ai_interviews AS PERMISSIVE FOR ALL TO public USING (true);
CREATE POLICY "rls_service_all" ON public.hr_auto_decisions AS PERMISSIVE FOR ALL TO public USING (true);
CREATE POLICY "rls_service_all" ON public.hr_auto_mode_config AS PERMISSIVE FOR ALL TO public USING (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.hr_goals;
CREATE POLICY "Authenticated access" ON public.hr_goals AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.messages;
CREATE POLICY "allow_all_messages_insert" ON public.messages AS PERMISSIVE FOR INSERT TO public WITH CHECK (true);
CREATE POLICY "allow_all_messages_read" ON public.messages AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY "allow_all_messages_update" ON public.messages AS PERMISSIVE FOR UPDATE TO public USING (true) WITH CHECK (true);
CREATE POLICY "tenant_isolation" ON public.sales_ab_assignments AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
CREATE POLICY "tenant_isolation" ON public.sales_ab_tests AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
CREATE POLICY "Tenant isolation for sales_consent_records" ON public.sales_consent_records AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
CREATE POLICY "Tenant isolation for sales_conversations" ON public.sales_conversations AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
CREATE POLICY "sales_conversations_policy" ON public.sales_conversations AS PERMISSIVE FOR ALL TO public USING (true);
CREATE POLICY "sales_dnc_policy" ON public.sales_do_not_contact AS PERMISSIVE FOR ALL TO public USING (true);
CREATE POLICY "allow_all_bridge" ON public.sales_marketing_bridge AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
CREATE POLICY "tenant_integrations_insert" ON public.tenant_integrations AS PERMISSIVE FOR INSERT TO authenticated, anon WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.aeo_brand_presence;
CREATE POLICY "auth_all_aeo_bp" ON public.aeo_brand_presence AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.aeo_content_scores;
CREATE POLICY "auth_all_aeo_cs" ON public.aeo_content_scores AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.aeo_entity_graph;
CREATE POLICY "auth_all_aeo_eg" ON public.aeo_entity_graph AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.aeo_schema_registry;
CREATE POLICY "auth_all_aeo_sr" ON public.aeo_schema_registry AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.ai_agent_metrics;
CREATE POLICY "ai_agent_metrics_read" ON public.ai_agent_metrics AS PERMISSIVE FOR SELECT TO public USING (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.ai_agents;
CREATE POLICY "ai_agents_anon_read" ON public.ai_agents AS PERMISSIVE FOR SELECT TO public USING (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.ai_decisions;
CREATE POLICY "Allow authenticated" ON public.ai_decisions AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.conversation_resolution_log;
CREATE POLICY "allow_all_conversation_resolution_log" ON public.conversation_resolution_log AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.hr_attendance;
CREATE POLICY "Authenticated access" ON public.hr_attendance AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.hr_attendance_rules;
CREATE POLICY "tenant_attendance_rules_all" ON public.hr_attendance_rules AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.hr_departments;
CREATE POLICY "Authenticated access" ON public.hr_departments AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.hr_document_acknowledgments;
CREATE POLICY "hr_doc_ack_all" ON public.hr_document_acknowledgments AS PERMISSIVE FOR ALL TO anon, authenticated, service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.hr_documents;
CREATE POLICY "Authenticated access" ON public.hr_documents AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.hr_leave_requests;
CREATE POLICY "Authenticated access" ON public.hr_leave_requests AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.hr_performance_cycles;
CREATE POLICY "Allow authenticated" ON public.hr_performance_cycles AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.hr_performance_reviews;
CREATE POLICY "Authenticated access" ON public.hr_performance_reviews AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.hr_training_programs;
CREATE POLICY "Authenticated access" ON public.hr_training_programs AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.hr_training_records;
CREATE POLICY "Authenticated access" ON public.hr_training_records AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.landing_pages;
CREATE POLICY "auth_all_landing_pages" ON public.landing_pages AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.marketing_calendar;
CREATE POLICY "auth_all_marketing_calendar" ON public.marketing_calendar AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.marketing_predictions;
CREATE POLICY "mkt_predictions_access" ON public.marketing_predictions AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.marketing_sequence_steps;
CREATE POLICY "Allow authenticated" ON public.marketing_sequence_steps AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.message_sentiment;
CREATE POLICY "allow_all_message_sentiment" ON public.message_sentiment AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.sla_breaches;
CREATE POLICY "allow_all_sla_breaches" ON public.sla_breaches AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.sla_policies;
CREATE POLICY "allow_all_sla_policies" ON public.sla_policies AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.video_performance_signals;
CREATE POLICY "allow_read_vps" ON public.video_performance_signals AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY "allow_write_vps" ON public.video_performance_signals AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.video_projects;
CREATE POLICY "auth_all_video_projects" ON public.video_projects AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.video_render_queue;
CREATE POLICY "auth_all_video_render_queue" ON public.video_render_queue AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.voice_inbox_sync;
CREATE POLICY "allow_all_voice_inbox_sync" ON public.voice_inbox_sync AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.clinic_consultations;
CREATE POLICY "clinic_consultations_tenant_isolation" ON public.clinic_consultations AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.tender_payments;
CREATE POLICY "allow_all" ON public.tender_payments AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.agent_contexts;
CREATE POLICY "ac_allow_all" ON public.agent_contexts AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.agent_memory;
CREATE POLICY "agent_memory_service" ON public.agent_memory AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.analytics_hourly;
CREATE POLICY "Allow authenticated" ON public.analytics_hourly AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.buying_committees;
CREATE POLICY "bc_all" ON public.buying_committees AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.campaign_executions;
CREATE POLICY "allow_all_campaign_executions" ON public.campaign_executions AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.collections_compliance_log;
CREATE POLICY "collections_compliance_log_tenant_access" ON public.collections_compliance_log AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.collections_kpis;
CREATE POLICY "collections_kpis_tenant_access" ON public.collections_kpis AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.consent_log;
CREATE POLICY "cl_all" ON public.consent_log AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.do_not_contact;
CREATE POLICY "Allow authenticated" ON public.do_not_contact AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.email_verification;
CREATE POLICY "ev_read" ON public.email_verification AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY "ev_write" ON public.email_verification AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.estimation_drawing_pages;
CREATE POLICY "allow_all_edp" ON public.estimation_drawing_pages AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.estimation_room_details;
CREATE POLICY "allow_read_rd" ON public.estimation_room_details AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY "allow_write_rd" ON public.estimation_room_details AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.estimation_room_polygons;
CREATE POLICY "allow_all_erp" ON public.estimation_room_polygons AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.estimation_spec_data;
CREATE POLICY "allow_read_sd" ON public.estimation_spec_data AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY "allow_write_sd" ON public.estimation_spec_data AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.estimation_supplier_pricing;
CREATE POLICY "allow_read_estimation_supplier_pricing" ON public.estimation_supplier_pricing AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY "allow_write_estimation_supplier_pricing" ON public.estimation_supplier_pricing AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.estimation_transition_rules;
CREATE POLICY "allow_read_tr" ON public.estimation_transition_rules AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY "allow_write_tr" ON public.estimation_transition_rules AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.estimation_waste_matrix;
CREATE POLICY "allow_read_wm" ON public.estimation_waste_matrix AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY "allow_write_wm" ON public.estimation_waste_matrix AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.field_job_cards;
CREATE POLICY "allow_all" ON public.field_job_cards AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.instrument_registry;
CREATE POLICY "allow_all" ON public.instrument_registry AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.lead_signals;
CREATE POLICY "ls_read" ON public.lead_signals AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY "ls_write" ON public.lead_signals AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.maintenance_contracts;
CREATE POLICY "allow_all" ON public.maintenance_contracts AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.multichannel_outreach;
CREATE POLICY "mco_all" ON public.multichannel_outreach AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.omega_alerts;
CREATE POLICY "allow_all_omega_alerts" ON public.omega_alerts AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.omega_campaigns;
CREATE POLICY "allow_all_omega_campaigns" ON public.omega_campaigns AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.onboarding_audit_log;
CREATE POLICY "oal_allow_all" ON public.onboarding_audit_log AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.onboarding_module_status;
CREATE POLICY "oms_allow_read" ON public.onboarding_module_status AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY "oms_allow_write" ON public.onboarding_module_status AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.ops_budget_actuals;
CREATE POLICY "allow_all" ON public.ops_budget_actuals AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.ops_budgets;
CREATE POLICY "allow_all" ON public.ops_budgets AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.ops_compliance_log;
CREATE POLICY "allow_all" ON public.ops_compliance_log AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.ops_compliance_rules;
CREATE POLICY "allow_all_ops_compliance_rules" ON public.ops_compliance_rules AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.ops_cost_savings;
CREATE POLICY "allow_all" ON public.ops_cost_savings AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.ops_demand_forecasts;
CREATE POLICY "allow_all" ON public.ops_demand_forecasts AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.ops_industry_configs;
CREATE POLICY "allow_all" ON public.ops_industry_configs AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.ops_inventory_items;
CREATE POLICY "allow_all" ON public.ops_inventory_items AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.ops_inventory_movements;
CREATE POLICY "allow_all" ON public.ops_inventory_movements AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.ops_production_plans;
CREATE POLICY "allow_all" ON public.ops_production_plans AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.ops_production_tasks;
CREATE POLICY "allow_all" ON public.ops_production_tasks AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.ops_purchase_orders;
CREATE POLICY "allow_all" ON public.ops_purchase_orders AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.ops_qc_checkpoints;
CREATE POLICY "allow_all" ON public.ops_qc_checkpoints AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.ops_qc_results;
CREATE POLICY "allow_all" ON public.ops_qc_results AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.ops_quality_alerts;
CREATE POLICY "allow_all_ops_quality_alerts" ON public.ops_quality_alerts AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.ops_quality_checks;
CREATE POLICY "allow_all_ops_quality_checks" ON public.ops_quality_checks AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.ops_shipment_events;
CREATE POLICY "allow_all" ON public.ops_shipment_events AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.ops_shipments;
CREATE POLICY "allow_all" ON public.ops_shipments AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.ops_simulations;
CREATE POLICY "allow_all" ON public.ops_simulations AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.ops_slas;
CREATE POLICY "allow_all" ON public.ops_slas AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.ops_vendor_performance;
CREATE POLICY "allow_all" ON public.ops_vendor_performance AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.ops_vendors;
CREATE POLICY "allow_all" ON public.ops_vendors AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.security_deposits;
CREATE POLICY "allow_all" ON public.security_deposits AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.sequence_ab_tests;
CREATE POLICY "sat_all" ON public.sequence_ab_tests AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.service_visits;
CREATE POLICY "allow_all" ON public.service_visits AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.tenant_audit_log;
CREATE POLICY "tenant_audit_log_authenticated_read" ON public.tenant_audit_log AS PERMISSIVE FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.tender_documents;
CREATE POLICY "allow_all" ON public.tender_documents AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.tender_stages;
CREATE POLICY "allow_all" ON public.tender_stages AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.tenders;
CREATE POLICY "allow_all" ON public.tenders AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.user_roles;
CREATE POLICY "Allow authenticated" ON public.user_roles AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.users;
CREATE POLICY "Allow authenticated" ON public.users AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
-- tenant_config [STEP5 undo]
DROP POLICY IF EXISTS "tenant_isolation_rls_fix" ON public.tenant_config;
CREATE POLICY "Authenticated can read config" ON public.tenant_config AS PERMISSIVE FOR SELECT TO authenticated USING (true);
