import { Integration, IntegrationCategory } from '@/types/integrations';

export const INTEGRATIONS: Integration[] = [
  // ============= COMMUNICATION (15) =============
  {
    id: 'whatsapp_wati',
    name: 'WhatsApp (WATI)',
    description: 'Send and receive WhatsApp messages via WATI',
    category: 'communication',
    icon: 'MessageCircle',
    color: '#25D366',
    authType: 'api_key',
    tier: 'starter',
    popular: true,
    features: ['Send messages', 'Receive messages', 'Template messages', 'Media support'],
    docsUrl: 'https://docs.wati.io',
    credentials: [
      { key: 'wati_endpoint', label: 'WATI Endpoint', type: 'url', placeholder: 'https://live-server-XXXX.wati.io', required: true, helpText: 'Your WATI server URL' },
      { key: 'wati_api_key', label: 'API Key', type: 'password', placeholder: 'Enter your WATI API key', required: true },
      { key: 'wati_phone_number', label: 'Phone Number', type: 'text', placeholder: '+1234567890', required: false, helpText: 'Your WhatsApp business number' },
    ],
    setupGuide: [
      'Log into your WATI dashboard',
      'Go to Settings > API Keys',
      'Copy your API key and endpoint URL',
      'Paste them here and save',
    ],
  },
  {
    id: 'whatsapp_cloud',
    name: 'WhatsApp Cloud API',
    description: 'Direct WhatsApp Business Cloud API integration',
    category: 'communication',
    icon: 'MessageCircle',
    color: '#25D366',
    authType: 'api_key',
    tier: 'professional',
    features: ['Direct API access', 'Webhooks', 'Template messages', 'Interactive messages'],
    docsUrl: 'https://developers.facebook.com/docs/whatsapp/cloud-api',
    credentials: [
      { key: 'whatsapp_phone_id', label: 'Phone Number ID', type: 'text', placeholder: 'Your Phone Number ID', required: true },
      { key: 'whatsapp_token', label: 'Access Token', type: 'password', placeholder: 'Permanent access token', required: true },
      { key: 'whatsapp_business_id', label: 'Business ID', type: 'text', placeholder: 'Your Business Account ID', required: true },
      { key: 'whatsapp_verify_token', label: 'Verify Token', type: 'text', placeholder: 'Webhook verification token', required: false },
    ],
  },
  {
    id: 'instagram',
    name: 'Instagram',
    description: 'Connect Instagram for DMs and content',
    category: 'communication',
    icon: 'Instagram',
    color: '#E4405F',
    authType: 'oauth',
    tier: 'professional',
    popular: true,
    features: ['Direct messages', 'Story replies', 'Comments', 'Media sharing'],
    credentials: [
      { key: 'instagram_page_id', label: 'Instagram Page ID', type: 'text', placeholder: 'Your Instagram Business Page ID', required: true },
      { key: 'instagram_token', label: 'Access Token', type: 'password', placeholder: 'Meta access token', required: true },
    ],
  },
  {
    id: 'facebook',
    name: 'Facebook Messenger',
    description: 'Connect Facebook Page for Messenger',
    category: 'communication',
    icon: 'Facebook',
    color: '#1877F2',
    authType: 'oauth',
    tier: 'starter',
    popular: true,
    features: ['Messenger inbox', 'Auto-replies', 'Rich messages', 'Quick replies'],
    credentials: [
      { key: 'meta_page_id', label: 'Facebook Page ID', type: 'text', placeholder: 'Your Facebook Page ID', required: true },
      { key: 'meta_page_token', label: 'Page Access Token', type: 'password', placeholder: 'Page access token', required: true },
      { key: 'meta_app_secret', label: 'App Secret', type: 'password', placeholder: 'Your app secret', required: false, helpText: 'Required for webhook verification' },
    ],
  },
  {
    id: 'telegram',
    name: 'Telegram',
    description: 'Connect Telegram bot for messaging',
    category: 'communication',
    icon: 'Send',
    color: '#0088CC',
    authType: 'api_key',
    tier: 'starter',
    features: ['Bot messages', 'Groups', 'Channels', 'Inline queries'],
    credentials: [
      { key: 'telegram_bot_token', label: 'Bot Token', type: 'password', placeholder: 'Your Telegram bot token from BotFather', required: true },
      { key: 'telegram_bot_username', label: 'Bot Username', type: 'text', placeholder: '@YourBotUsername', required: false },
    ],
    setupGuide: [
      'Open Telegram and search for @BotFather',
      'Send /newbot and follow the prompts',
      'Copy the bot token provided',
      'Paste the token here',
    ],
  },
  {
    id: 'twitter',
    name: 'Twitter / X',
    description: 'Connect Twitter for DMs and mentions',
    category: 'communication',
    icon: 'Twitter',
    color: '#1DA1F2',
    authType: 'oauth',
    tier: 'professional',
    features: ['Direct messages', 'Mentions', 'Tweet replies', 'Analytics'],
    credentials: [
      { key: 'twitter_bearer_token', label: 'Bearer Token', type: 'password', placeholder: 'Your Twitter bearer token', required: true },
      { key: 'twitter_api_key', label: 'API Key', type: 'password', placeholder: 'API Key (Consumer Key)', required: true },
      { key: 'twitter_api_secret', label: 'API Secret', type: 'password', placeholder: 'API Secret', required: true },
      { key: 'twitter_access_token', label: 'Access Token', type: 'password', placeholder: 'User access token', required: true },
      { key: 'twitter_access_secret', label: 'Access Secret', type: 'password', placeholder: 'User access secret', required: true },
    ],
  },
  {
    id: 'sms_twilio',
    name: 'Twilio SMS',
    description: 'Send and receive SMS via Twilio',
    category: 'communication',
    icon: 'MessageSquare',
    color: '#F22F46',
    authType: 'api_key',
    tier: 'starter',
    popular: true,
    features: ['Send SMS', 'Receive SMS', 'MMS support', 'Delivery reports'],
    docsUrl: 'https://www.twilio.com/docs/sms',
    credentials: [
      { key: 'twilio_account_sid', label: 'Account SID', type: 'text', placeholder: 'Your Twilio Account SID', required: true },
      { key: 'twilio_auth_token', label: 'Auth Token', type: 'password', placeholder: 'Your Twilio Auth Token', required: true },
      { key: 'twilio_phone_number', label: 'Phone Number', type: 'text', placeholder: '+1234567890', required: true, helpText: 'Your Twilio phone number' },
      { key: 'twilio_messaging_service_sid', label: 'Messaging Service SID', type: 'text', placeholder: 'Optional: Messaging Service SID', required: false },
    ],
  },
  {
    id: 'linkedin',
    name: 'LinkedIn',
    description: 'Connect LinkedIn for messaging and posts',
    category: 'communication',
    icon: 'Linkedin',
    color: '#0A66C2',
    authType: 'oauth',
    tier: 'enterprise',
    features: ['InMail', 'Connection requests', 'Company posts', 'Lead sync'],
    credentials: [
      { key: 'linkedin_access_token', label: 'Access Token', type: 'password', placeholder: 'LinkedIn OAuth access token', required: true },
      { key: 'linkedin_refresh_token', label: 'Refresh Token', type: 'password', placeholder: 'LinkedIn OAuth refresh token', required: false },
      { key: 'linkedin_org_id', label: 'Organization ID', type: 'text', placeholder: 'Your LinkedIn Company ID', required: false },
    ],
  },
  {
    id: 'email_smtp',
    name: 'SMTP Email',
    description: 'Send emails via any SMTP server',
    category: 'communication',
    icon: 'Mail',
    color: '#EA4335',
    authType: 'credentials',
    tier: 'starter',
    features: ['Send emails', 'HTML emails', 'Attachments', 'Custom domains'],
    credentials: [
      { key: 'smtp_host', label: 'SMTP Host', type: 'text', placeholder: 'smtp.example.com', required: true },
      { key: 'smtp_port', label: 'SMTP Port', type: 'number', placeholder: '587', required: true },
      { key: 'smtp_user', label: 'Username', type: 'text', placeholder: 'Your SMTP username', required: true },
      { key: 'smtp_pass', label: 'Password', type: 'password', placeholder: 'Your SMTP password', required: true },
      { key: 'smtp_from_email', label: 'From Email', type: 'email', placeholder: 'noreply@yourdomain.com', required: true },
      { key: 'smtp_from_name', label: 'From Name', type: 'text', placeholder: 'Your Company Name', required: false },
    ],
  },
  {
    id: 'email_sendgrid',
    name: 'SendGrid',
    description: 'Transactional and marketing emails',
    category: 'communication',
    icon: 'Mail',
    color: '#1A82E2',
    authType: 'api_key',
    tier: 'starter',
    popular: true,
    features: ['Transactional emails', 'Templates', 'Analytics', 'Deliverability'],
    docsUrl: 'https://docs.sendgrid.com',
    credentials: [
      { key: 'sendgrid_api_key', label: 'API Key', type: 'password', placeholder: 'SG.xxxxxxxxx', required: true },
    ],
  },
  {
    id: 'email_mailgun',
    name: 'Mailgun',
    description: 'Email API for developers',
    category: 'communication',
    icon: 'Mail',
    color: '#F06B66',
    authType: 'api_key',
    tier: 'starter',
    features: ['Email API', 'Routing', 'Validation', 'Analytics'],
    docsUrl: 'https://documentation.mailgun.com',
    credentials: [
      { key: 'mailgun_api_key', label: 'API Key', type: 'password', placeholder: 'Your Mailgun API key', required: true },
      { key: 'mailgun_domain', label: 'Domain', type: 'text', placeholder: 'mg.yourdomain.com', required: true },
    ],
  },
  {
    id: 'voice_vapi',
    name: 'VAPI Voice AI',
    description: 'AI-powered voice assistants',
    category: 'communication',
    icon: 'Phone',
    color: '#6366F1',
    authType: 'api_key',
    tier: 'professional',
    popular: true,
    features: ['AI voice calls', 'Custom assistants', 'Call routing', 'Transcriptions'],
    docsUrl: 'https://docs.vapi.ai',
    credentials: [
      { key: 'vapi_api_key', label: 'API Key', type: 'password', placeholder: 'Your VAPI API key', required: true },
      { key: 'vapi_assistant_id', label: 'Assistant ID', type: 'text', placeholder: 'Your default assistant ID', required: false },
      { key: 'vapi_phone_number', label: 'Phone Number', type: 'text', placeholder: 'Your VAPI phone number', required: false },
    ],
  },
  {
    id: 'voice_twilio',
    name: 'Twilio Voice',
    description: 'Voice calls via Twilio',
    category: 'communication',
    icon: 'Phone',
    color: '#F22F46',
    authType: 'api_key',
    tier: 'professional',
    features: ['Inbound calls', 'Outbound calls', 'IVR', 'Call recording'],
    credentials: [
      { key: 'twilio_account_sid', label: 'Account SID', type: 'text', placeholder: 'Your Twilio Account SID', required: true },
      { key: 'twilio_auth_token', label: 'Auth Token', type: 'password', placeholder: 'Your Twilio Auth Token', required: true },
      { key: 'twilio_voice_phone', label: 'Voice Phone Number', type: 'text', placeholder: '+1234567890', required: true },
    ],
  },
  {
    id: 'website_chat',
    name: 'Website Chat Widget',
    description: 'Embed chat widget on your website',
    category: 'communication',
    icon: 'MessageSquare',
    color: '#3B82F6',
    authType: 'api_key',
    tier: 'starter',
    features: ['Live chat', 'AI responses', 'Custom styling', 'Lead capture'],
    credentials: [
      { key: 'website_chat_enabled', label: 'Enable Widget', type: 'select', required: true, options: [{ label: 'Enabled', value: 'true' }, { label: 'Disabled', value: 'false' }] },
      { key: 'website_chat_domains', label: 'Allowed Domains', type: 'textarea', placeholder: 'yourdomain.com\nwww.yourdomain.com', required: false, helpText: 'One domain per line' },
    ],
    settings: [
      { key: 'widget_color', label: 'Widget Color', type: 'color', defaultValue: '#3B82F6' },
      { key: 'widget_position', label: 'Position', type: 'select', defaultValue: 'bottom-right', options: [{ label: 'Bottom Right', value: 'bottom-right' }, { label: 'Bottom Left', value: 'bottom-left' }] },
      { key: 'auto_greeting', label: 'Auto Greeting', type: 'boolean', defaultValue: true },
    ],
  },
  {
    id: 'tiktok',
    name: 'TikTok',
    description: 'Connect TikTok for messaging and content',
    category: 'communication',
    icon: 'Music',
    color: '#000000',
    authType: 'oauth',
    tier: 'enterprise',
    comingSoon: true,
    features: ['Direct messages', 'Comments', 'Analytics'],
    credentials: [],
  },

  // ============= SCHEDULING (4) =============
  {
    id: 'google_calendar',
    name: 'Google Calendar',
    description: 'Sync with Google Calendar',
    category: 'scheduling',
    icon: 'Calendar',
    color: '#4285F4',
    authType: 'oauth',
    tier: 'starter',
    popular: true,
    features: ['Two-way sync', 'Event creation', 'Reminders', 'Availability'],
    docsUrl: 'https://developers.google.com/calendar',
    credentials: [
      { key: 'google_calendar_id', label: 'Calendar ID', type: 'text', placeholder: 'your-calendar@group.calendar.google.com', required: true },
      { key: 'google_access_token', label: 'Access Token', type: 'password', placeholder: 'OAuth access token', required: true },
      { key: 'google_refresh_token', label: 'Refresh Token', type: 'password', placeholder: 'OAuth refresh token', required: false },
    ],
  },
  {
    id: 'outlook_calendar',
    name: 'Outlook Calendar',
    description: 'Sync with Microsoft Outlook Calendar',
    category: 'scheduling',
    icon: 'Calendar',
    color: '#0078D4',
    authType: 'oauth',
    tier: 'starter',
    features: ['Two-way sync', 'Event creation', 'Teams integration'],
    credentials: [
      { key: 'outlook_calendar_id', label: 'Calendar ID', type: 'text', placeholder: 'Calendar ID', required: true },
      { key: 'outlook_access_token', label: 'Access Token', type: 'password', placeholder: 'OAuth access token', required: true },
      { key: 'outlook_refresh_token', label: 'Refresh Token', type: 'password', placeholder: 'OAuth refresh token', required: false },
    ],
  },
  {
    id: 'calendly',
    name: 'Calendly',
    description: 'Scheduling and booking automation',
    category: 'scheduling',
    icon: 'CalendarDays',
    color: '#006BFF',
    authType: 'api_key',
    tier: 'starter',
    popular: true,
    features: ['Booking pages', 'Webhooks', 'Event types', 'Team scheduling'],
    docsUrl: 'https://developer.calendly.com',
    credentials: [
      { key: 'calendly_api_key', label: 'API Key', type: 'password', placeholder: 'Your Calendly API key', required: true },
      { key: 'calendly_user_uri', label: 'User URI', type: 'url', placeholder: 'https://api.calendly.com/users/XXXXX', required: true },
    ],
  },
  {
    id: 'acuity',
    name: 'Acuity Scheduling',
    description: 'Appointment scheduling software',
    category: 'scheduling',
    icon: 'CalendarCheck',
    color: '#1AB394',
    authType: 'api_key',
    tier: 'starter',
    features: ['Online booking', 'Payments', 'Reminders', 'Forms'],
    credentials: [
      { key: 'acuity_user_id', label: 'User ID', type: 'text', placeholder: 'Your Acuity User ID', required: true },
      { key: 'acuity_api_key', label: 'API Key', type: 'password', placeholder: 'Your Acuity API key', required: true },
    ],
  },

  // ============= PAYMENTS (4) =============
  {
    id: 'stripe',
    name: 'Stripe',
    description: 'Accept payments with Stripe',
    category: 'payments',
    icon: 'CreditCard',
    color: '#635BFF',
    authType: 'api_key',
    tier: 'starter',
    popular: true,
    features: ['Card payments', 'Subscriptions', 'Invoicing', 'Connect'],
    docsUrl: 'https://stripe.com/docs',
    credentials: [
      { key: 'stripe_secret_key', label: 'Secret Key', type: 'password', placeholder: 'sk_live_...', required: true },
      { key: 'stripe_publishable_key', label: 'Publishable Key', type: 'text', placeholder: 'pk_live_...', required: true },
      { key: 'stripe_webhook_secret', label: 'Webhook Secret', type: 'password', placeholder: 'whsec_...', required: false },
    ],
    settings: [
      { key: 'currency', label: 'Default Currency', type: 'select', defaultValue: 'USD', options: [{ label: 'USD', value: 'USD' }, { label: 'EUR', value: 'EUR' }, { label: 'GBP', value: 'GBP' }, { label: 'AED', value: 'AED' }] },
      { key: 'deposit_enabled', label: 'Enable Deposits', type: 'boolean', defaultValue: false },
      { key: 'deposit_percentage', label: 'Deposit %', type: 'number', defaultValue: 50 },
    ],
  },
  {
    id: 'paypal',
    name: 'PayPal',
    description: 'Accept PayPal payments',
    category: 'payments',
    icon: 'DollarSign',
    color: '#003087',
    authType: 'api_key',
    tier: 'starter',
    features: ['PayPal checkout', 'Invoicing', 'Subscriptions'],
    credentials: [
      { key: 'paypal_client_id', label: 'Client ID', type: 'text', placeholder: 'Your PayPal Client ID', required: true },
      { key: 'paypal_client_secret', label: 'Client Secret', type: 'password', placeholder: 'Your PayPal Client Secret', required: true },
      { key: 'paypal_mode', label: 'Mode', type: 'select', required: true, options: [{ label: 'Sandbox', value: 'sandbox' }, { label: 'Live', value: 'live' }] },
    ],
  },
  {
    id: 'square',
    name: 'Square',
    description: 'Accept payments with Square',
    category: 'payments',
    icon: 'CreditCard',
    color: '#006AFF',
    authType: 'api_key',
    tier: 'starter',
    features: ['Card payments', 'Invoicing', 'Terminals'],
    credentials: [
      { key: 'square_access_token', label: 'Access Token', type: 'password', placeholder: 'Your Square access token', required: true },
      { key: 'square_location_id', label: 'Location ID', type: 'text', placeholder: 'Your Square location ID', required: true },
      { key: 'square_environment', label: 'Environment', type: 'select', required: true, options: [{ label: 'Sandbox', value: 'sandbox' }, { label: 'Production', value: 'production' }] },
    ],
  },
  {
    id: 'razorpay',
    name: 'Razorpay',
    description: 'Accept payments in India',
    category: 'payments',
    icon: 'CreditCard',
    color: '#072654',
    authType: 'api_key',
    tier: 'starter',
    features: ['UPI', 'Cards', 'Net banking', 'Subscriptions'],
    credentials: [
      { key: 'razorpay_key_id', label: 'Key ID', type: 'text', placeholder: 'rzp_live_...', required: true },
      { key: 'razorpay_key_secret', label: 'Key Secret', type: 'password', placeholder: 'Your Razorpay key secret', required: true },
    ],
  },

  // ============= CRM (5) =============
  {
    id: 'hubspot',
    name: 'HubSpot',
    description: 'Sync with HubSpot CRM',
    category: 'crm',
    icon: 'Users',
    color: '#FF7A59',
    authType: 'oauth',
    tier: 'professional',
    popular: true,
    features: ['Contact sync', 'Deal sync', 'Activity logging', 'Workflows'],
    docsUrl: 'https://developers.hubspot.com',
    credentials: [
      { key: 'hubspot_access_token', label: 'Access Token', type: 'password', placeholder: 'Your HubSpot access token', required: true },
      { key: 'hubspot_refresh_token', label: 'Refresh Token', type: 'password', placeholder: 'HubSpot refresh token', required: false },
      { key: 'hubspot_portal_id', label: 'Portal ID', type: 'text', placeholder: 'Your HubSpot Portal ID', required: true },
    ],
  },
  {
    id: 'salesforce',
    name: 'Salesforce',
    description: 'Sync with Salesforce CRM',
    category: 'crm',
    icon: 'Cloud',
    color: '#00A1E0',
    authType: 'oauth',
    tier: 'enterprise',
    features: ['Lead sync', 'Opportunity sync', 'Custom objects', 'Reports'],
    credentials: [
      { key: 'salesforce_instance_url', label: 'Instance URL', type: 'url', placeholder: 'https://yourorg.my.salesforce.com', required: true },
      { key: 'salesforce_access_token', label: 'Access Token', type: 'password', placeholder: 'Salesforce access token', required: true },
      { key: 'salesforce_refresh_token', label: 'Refresh Token', type: 'password', placeholder: 'Salesforce refresh token', required: false },
    ],
  },
  {
    id: 'pipedrive',
    name: 'Pipedrive',
    description: 'Sync with Pipedrive CRM',
    category: 'crm',
    icon: 'Target',
    color: '#1B1B1B',
    authType: 'api_key',
    tier: 'professional',
    features: ['Deal sync', 'Contact sync', 'Activities', 'Pipelines'],
    credentials: [
      { key: 'pipedrive_api_token', label: 'API Token', type: 'password', placeholder: 'Your Pipedrive API token', required: true },
      { key: 'pipedrive_company_domain', label: 'Company Domain', type: 'text', placeholder: 'yourcompany.pipedrive.com', required: true },
    ],
  },
  {
    id: 'zoho_crm',
    name: 'Zoho CRM',
    description: 'Sync with Zoho CRM',
    category: 'crm',
    icon: 'Database',
    color: '#C8202B',
    authType: 'oauth',
    tier: 'professional',
    features: ['Lead sync', 'Deal sync', 'Modules', 'Workflows'],
    credentials: [
      { key: 'zoho_access_token', label: 'Access Token', type: 'password', placeholder: 'Zoho access token', required: true },
      { key: 'zoho_refresh_token', label: 'Refresh Token', type: 'password', placeholder: 'Zoho refresh token', required: false },
      { key: 'zoho_api_domain', label: 'API Domain', type: 'select', required: true, options: [{ label: 'zoho.com', value: 'https://www.zohoapis.com' }, { label: 'zoho.eu', value: 'https://www.zohoapis.eu' }, { label: 'zoho.in', value: 'https://www.zohoapis.in' }] },
    ],
  },
  {
    id: 'freshsales',
    name: 'Freshsales',
    description: 'Sync with Freshsales CRM',
    category: 'crm',
    icon: 'Briefcase',
    color: '#13C26B',
    authType: 'api_key',
    tier: 'professional',
    features: ['Lead management', 'Sales sequences', 'Built-in phone'],
    credentials: [
      { key: 'freshsales_api_key', label: 'API Key', type: 'password', placeholder: 'Your Freshsales API key', required: true },
      { key: 'freshsales_domain', label: 'Domain', type: 'text', placeholder: 'yourcompany.freshsales.io', required: true },
    ],
  },

  // ============= SUPPORT (3) =============
  {
    id: 'zendesk',
    name: 'Zendesk',
    description: 'Help desk and support tickets',
    category: 'support',
    icon: 'Headphones',
    color: '#03363D',
    authType: 'api_key',
    tier: 'professional',
    popular: true,
    features: ['Ticket sync', 'Customer data', 'Macros', 'Automation'],
    credentials: [
      { key: 'zendesk_subdomain', label: 'Subdomain', type: 'text', placeholder: 'yourcompany', required: true, helpText: 'yourcompany.zendesk.com' },
      { key: 'zendesk_email', label: 'Admin Email', type: 'email', placeholder: 'admin@company.com', required: true },
      { key: 'zendesk_api_token', label: 'API Token', type: 'password', placeholder: 'Your Zendesk API token', required: true },
    ],
  },
  {
    id: 'intercom',
    name: 'Intercom',
    description: 'Customer messaging platform',
    category: 'support',
    icon: 'MessageSquare',
    color: '#1F8DED',
    authType: 'api_key',
    tier: 'professional',
    features: ['Live chat', 'Help articles', 'Bots', 'Product tours'],
    credentials: [
      { key: 'intercom_access_token', label: 'Access Token', type: 'password', placeholder: 'Your Intercom access token', required: true },
      { key: 'intercom_app_id', label: 'App ID', type: 'text', placeholder: 'Your Intercom App ID', required: true },
    ],
  },
  {
    id: 'freshdesk',
    name: 'Freshdesk',
    description: 'Customer support software',
    category: 'support',
    icon: 'LifeBuoy',
    color: '#1DCE73',
    authType: 'api_key',
    tier: 'professional',
    features: ['Ticketing', 'Knowledge base', 'Automation', 'Reporting'],
    credentials: [
      { key: 'freshdesk_api_key', label: 'API Key', type: 'password', placeholder: 'Your Freshdesk API key', required: true },
      { key: 'freshdesk_domain', label: 'Domain', type: 'text', placeholder: 'yourcompany.freshdesk.com', required: true },
    ],
  },

  // ============= E-COMMERCE (2) =============
  {
    id: 'shopify',
    name: 'Shopify',
    description: 'Connect your Shopify store',
    category: 'ecommerce',
    icon: 'ShoppingBag',
    color: '#7AB55C',
    authType: 'api_key',
    tier: 'professional',
    popular: true,
    features: ['Order sync', 'Customer sync', 'Products', 'Inventory'],
    credentials: [
      { key: 'shopify_shop_domain', label: 'Shop Domain', type: 'text', placeholder: 'yourstore.myshopify.com', required: true },
      { key: 'shopify_access_token', label: 'Access Token', type: 'password', placeholder: 'Your Shopify access token', required: true },
    ],
  },
  {
    id: 'woocommerce',
    name: 'WooCommerce',
    description: 'Connect your WooCommerce store',
    category: 'ecommerce',
    icon: 'ShoppingCart',
    color: '#96588A',
    authType: 'api_key',
    tier: 'professional',
    features: ['Order sync', 'Customer sync', 'Products', 'Webhooks'],
    credentials: [
      { key: 'woocommerce_url', label: 'Store URL', type: 'url', placeholder: 'https://yourstore.com', required: true },
      { key: 'woocommerce_consumer_key', label: 'Consumer Key', type: 'text', placeholder: 'ck_...', required: true },
      { key: 'woocommerce_consumer_secret', label: 'Consumer Secret', type: 'password', placeholder: 'cs_...', required: true },
    ],
  },

  // ============= AI & ENRICHMENT (8) =============
  {
    id: 'openai',
    name: 'OpenAI',
    description: 'GPT and AI capabilities',
    category: 'ai',
    icon: 'Brain',
    color: '#10A37F',
    authType: 'api_key',
    tier: 'starter',
    popular: true,
    features: ['GPT models', 'Embeddings', 'Fine-tuning', 'Assistants'],
    docsUrl: 'https://platform.openai.com/docs',
    credentials: [
      { key: 'openai_api_key', label: 'API Key', type: 'password', placeholder: 'sk-...', required: true },
      { key: 'openai_org_id', label: 'Organization ID', type: 'text', placeholder: 'org-...', required: false },
    ],
    settings: [
      { key: 'model', label: 'Default Model', type: 'select', defaultValue: 'gpt-4o-mini', options: [{ label: 'GPT-4o', value: 'gpt-4o' }, { label: 'GPT-4o Mini', value: 'gpt-4o-mini' }, { label: 'GPT-4 Turbo', value: 'gpt-4-turbo' }, { label: 'GPT-3.5 Turbo', value: 'gpt-3.5-turbo' }] },
      { key: 'temperature', label: 'Temperature', type: 'number', defaultValue: 0.7, helpText: '0-2, lower is more focused' },
    ],
  },
  {
    id: 'anthropic',
    name: 'Anthropic Claude',
    description: 'Claude AI models',
    category: 'ai',
    icon: 'Sparkles',
    color: '#D97706',
    authType: 'api_key',
    tier: 'professional',
    features: ['Claude models', 'Long context', 'Analysis', 'Coding'],
    credentials: [
      { key: 'anthropic_api_key', label: 'API Key', type: 'password', placeholder: 'sk-ant-...', required: true },
    ],
  },
  {
    id: 'apify',
    name: 'Apify',
    description: 'Web scraping and automation',
    category: 'ai',
    icon: 'Globe',
    color: '#00C2A8',
    authType: 'api_key',
    tier: 'professional',
    popular: true,
    features: ['Web scraping', 'Data extraction', 'Actors', 'Scheduling'],
    docsUrl: 'https://docs.apify.com',
    credentials: [
      { key: 'apify_api_key', label: 'API Token', type: 'password', placeholder: 'Your Apify API token', required: true },
    ],
  },
  {
    id: 'apollo',
    name: 'Apollo.io',
    description: 'B2B lead enrichment and data',
    category: 'ai',
    icon: 'Users',
    color: '#5850EC',
    authType: 'api_key',
    tier: 'professional',
    popular: true,
    features: ['Lead enrichment', 'Email finder', 'Company data', 'Sequences'],
    credentials: [
      { key: 'apollo_api_key', label: 'API Key', type: 'password', placeholder: 'Your Apollo API key', required: true },
    ],
  },
  {
    id: 'hunter',
    name: 'Hunter.io',
    description: 'Email finder and verification',
    category: 'ai',
    icon: 'Search',
    color: '#FF6B00',
    authType: 'api_key',
    tier: 'professional',
    features: ['Email finder', 'Verification', 'Domain search', 'Bulk tasks'],
    credentials: [
      { key: 'hunter_api_key', label: 'API Key', type: 'password', placeholder: 'Your Hunter API key', required: true },
    ],
  },
  {
    id: 'clearbit',
    name: 'Clearbit',
    description: 'Data enrichment and reveal',
    category: 'ai',
    icon: 'Database',
    color: '#3B55E6',
    authType: 'api_key',
    tier: 'enterprise',
    features: ['Company data', 'Person data', 'Reveal', 'Enrichment'],
    credentials: [
      { key: 'clearbit_api_key', label: 'API Key', type: 'password', placeholder: 'Your Clearbit API key', required: true },
    ],
  },
  {
    id: 'zoominfo',
    name: 'ZoomInfo',
    description: 'B2B contact and company data',
    category: 'ai',
    icon: 'Building',
    color: '#1D9E00',
    authType: 'api_key',
    tier: 'enterprise',
    features: ['Contact data', 'Intent data', 'Technographics', 'Org charts'],
    credentials: [
      { key: 'zoominfo_api_key', label: 'API Key', type: 'password', placeholder: 'Your ZoomInfo API key', required: true },
    ],
  },
  {
    id: 'google_search',
    name: 'Google Custom Search',
    description: 'Google Search API for prospecting',
    category: 'ai',
    icon: 'Search',
    color: '#4285F4',
    authType: 'api_key',
    tier: 'starter',
    features: ['Web search', 'Custom results', 'Image search'],
    credentials: [
      { key: 'google_api_key', label: 'API Key', type: 'password', placeholder: 'Your Google API key', required: true },
      { key: 'google_cx', label: 'Search Engine ID', type: 'text', placeholder: 'Your Custom Search Engine ID', required: true },
    ],
  },

  // ============= PRODUCTIVITY (4) =============
  {
    id: 'slack',
    name: 'Slack',
    description: 'Send notifications to Slack',
    category: 'productivity',
    icon: 'Hash',
    color: '#4A154B',
    authType: 'webhook',
    tier: 'starter',
    popular: true,
    features: ['Notifications', 'Alerts', 'Channel posting', 'Bot messages'],
    credentials: [
      { key: 'slack_webhook_url', label: 'Webhook URL', type: 'url', placeholder: 'https://hooks.slack.com/services/...', required: true },
      { key: 'slack_bot_token', label: 'Bot Token', type: 'password', placeholder: 'xoxb-...', required: false },
      { key: 'slack_channel_id', label: 'Default Channel', type: 'text', placeholder: '#general or C0XXXXXXX', required: false },
    ],
  },
  {
    id: 'zapier',
    name: 'Zapier',
    description: 'Connect 5000+ apps via Zapier',
    category: 'productivity',
    icon: 'Zap',
    color: '#FF4A00',
    authType: 'webhook',
    tier: 'starter',
    popular: true,
    features: ['Triggers', 'Actions', 'Multi-step Zaps', 'Filters'],
    credentials: [
      { key: 'zapier_webhook_url', label: 'Webhook URL', type: 'url', placeholder: 'https://hooks.zapier.com/...', required: true },
    ],
  },
  {
    id: 'google_sheets',
    name: 'Google Sheets',
    description: 'Sync data with Google Sheets',
    category: 'productivity',
    icon: 'Sheet',
    color: '#0F9D58',
    authType: 'api_key',
    tier: 'starter',
    features: ['Read/write data', 'Sync contacts', 'Export reports'],
    credentials: [
      { key: 'google_sheets_id', label: 'Spreadsheet ID', type: 'text', placeholder: 'Spreadsheet ID from URL', required: true },
      { key: 'google_service_account', label: 'Service Account JSON', type: 'textarea', placeholder: '{"type":"service_account",...}', required: true },
    ],
  },
  {
    id: 'notion',
    name: 'Notion',
    description: 'Sync with Notion databases',
    category: 'productivity',
    icon: 'FileText',
    color: '#000000',
    authType: 'api_key',
    tier: 'professional',
    features: ['Database sync', 'Page creation', 'Comments', 'Blocks'],
    credentials: [
      { key: 'notion_api_key', label: 'Integration Token', type: 'password', placeholder: 'secret_...', required: true },
      { key: 'notion_database_id', label: 'Database ID', type: 'text', placeholder: 'Your Notion database ID', required: false },
    ],
  },

  // ============= ANALYTICS (3) =============
  {
    id: 'google_analytics',
    name: 'Google Analytics',
    description: 'Track website analytics',
    category: 'analytics',
    icon: 'LineChart',
    color: '#E37400',
    authType: 'api_key',
    tier: 'starter',
    features: ['Page views', 'Events', 'Conversions', 'Audiences'],
    credentials: [
      { key: 'ga_measurement_id', label: 'Measurement ID', type: 'text', placeholder: 'G-XXXXXXXXXX', required: true },
      { key: 'ga_api_secret', label: 'API Secret', type: 'password', placeholder: 'Your GA4 API secret', required: false },
    ],
  },
  {
    id: 'mixpanel',
    name: 'Mixpanel',
    description: 'Product analytics platform',
    category: 'analytics',
    icon: 'PieChart',
    color: '#7856FF',
    authType: 'api_key',
    tier: 'professional',
    features: ['Event tracking', 'Funnels', 'Cohorts', 'A/B testing'],
    credentials: [
      { key: 'mixpanel_token', label: 'Project Token', type: 'text', placeholder: 'Your Mixpanel project token', required: true },
      { key: 'mixpanel_api_secret', label: 'API Secret', type: 'password', placeholder: 'For server-side tracking', required: false },
    ],
  },
  {
    id: 'segment',
    name: 'Segment',
    description: 'Customer data platform',
    category: 'analytics',
    icon: 'Share2',
    color: '#52BD95',
    authType: 'api_key',
    tier: 'professional',
    features: ['Data collection', 'Destinations', 'Identity', 'Protocols'],
    credentials: [
      { key: 'segment_write_key', label: 'Write Key', type: 'password', placeholder: 'Your Segment write key', required: true },
    ],
  },

  // ============= FORMS (2) =============
  {
    id: 'typeform',
    name: 'Typeform',
    description: 'Connect Typeform responses',
    category: 'forms',
    icon: 'FileInput',
    color: '#262627',
    authType: 'api_key',
    tier: 'starter',
    features: ['Form responses', 'Webhooks', 'Lead capture'],
    credentials: [
      { key: 'typeform_api_key', label: 'Personal Access Token', type: 'password', placeholder: 'Your Typeform access token', required: true },
    ],
  },
  {
    id: 'jotform',
    name: 'JotForm',
    description: 'Connect JotForm submissions',
    category: 'forms',
    icon: 'ClipboardList',
    color: '#0A1551',
    authType: 'api_key',
    tier: 'starter',
    features: ['Form submissions', 'Webhooks', 'Payments'],
    credentials: [
      { key: 'jotform_api_key', label: 'API Key', type: 'password', placeholder: 'Your JotForm API key', required: true },
    ],
  },
];

// Helper to get integration by ID
export const getIntegration = (id: string): Integration | undefined => {
  return INTEGRATIONS.find(i => i.id === id);
};

// Helper to get integrations by category
export const getIntegrationsByCategory = (category: IntegrationCategory): Integration[] => {
  return INTEGRATIONS.filter(i => i.category === category);
};

// Group integrations by category
export const getIntegrationsGroupedByCategory = (): Record<IntegrationCategory, Integration[]> => {
  return INTEGRATIONS.reduce((acc, integration) => {
    if (!acc[integration.category]) {
      acc[integration.category] = [];
    }
    acc[integration.category].push(integration);
    return acc;
  }, {} as Record<IntegrationCategory, Integration[]>);
};
